"""
Save small session context.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import state


SESSION_SNAPSHOT_MAX_BYTES = 28672


def find_repo_root() -> Path | None:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            return Path(result.stdout.strip())
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None
    return None


def session_summary(payload: dict) -> str:
    text = payload.get("last_assistant_message") or ""
    return text[:280] + ("..." if len(text) > 280 else "")


def write_session_snapshot(repo_root: Path, summary: str, workflow: dict) -> None:
    content = [
        "# Anyone Can Code - Session Snapshot",
        "",
        "## Workflow Snapshot",
        f"- Phase: {workflow.get('phase', 'idle')}",
        f"- Route: {workflow.get('route', 'unknown')}",
        f"- Entry mode: {workflow.get('entry_mode', 'unknown')}",
        f"- Last task: {workflow.get('last_task', 'N/A')}",
        f"- Next step: {workflow.get('next_step', 'N/A')}",
        f"- Communication mode: {workflow.get('communication_mode', 'normal')}",
        f"- Memory mode: {workflow.get('memory_mode', 'portable-markdown')}",
        "",
        "## Last Session",
        summary or "No assistant summary was available.",
        "",
        "## Notes",
        "This file is generated by Anyone Can Code hooks and is safe to refresh.",
    ]
    text = "\n".join(content) + "\n"
    encoded = text.encode("utf-8")
    if len(encoded) > SESSION_SNAPSHOT_MAX_BYTES:
        text = encoded[:SESSION_SNAPSHOT_MAX_BYTES].decode("utf-8", errors="ignore")
        text = text[: text.rfind("\n")] + "\n"
    layout = state.ensure_project_layout(repo_root)
    (layout["state"] / "session-snapshot.md").write_text(text, encoding="utf-8")


def infer_next_step(summary: str) -> str:
    lower = summary.lower()
    if any(token in lower for token in ["fix", "error", "failure"]):
        return "Use $verify or $resume. Fix failure first."
    if any(token in lower for token in ["verify", "review"]):
        return "If clean, go on. If bad, fix."
    if any(token in lower for token in ["plan", "spec"]):
        return "Plan good. Build next."
    if any(token in lower for token in ["build", "implement", "change"]):
        return "Check result before done."
    return "Use front door or $status."


def recent_signal_summary(repo_root: Path) -> tuple[str, list[dict]]:
    signals = state.read_recent_jsonl(state.signal_log_path(repo_root), limit=12)
    if not signals:
        return "No recent signals.", []
    recent_types = [row.get("signal_type", "unknown") for row in signals[-5:]]
    return f"Recent signals: {', '.join(recent_types)}.", signals


def write_mistake_ledger(repo_root: Path, signals: list[dict]) -> None:
    for row in signals:
        if row.get("signal_type") in {"style_correction", "user_correction", "wrong_context", "repeated_failure"}:
            state.append_jsonl(
                state.mistake_log_path(repo_root),
                {
                    "timestamp": row.get("timestamp", state.utc_now()),
                    "signal_type": row.get("signal_type"),
                    "detail": row.get("detail", ""),
                },
            )


def maybe_import_memory_server():
    plugin_root = os.environ.get("PLUGIN_ROOT")
    if not plugin_root:
        return None
    server_path = Path(plugin_root) / "mcp"
    if not server_path.exists():
        return None
    sys.path.insert(0, str(server_path))
    try:
        import server  # type: ignore

        return server
    except Exception:
        return None


def durable_memory_writes(repo_root: Path, signals: list[dict], summary: str) -> None:
    server = maybe_import_memory_server()
    if server is None:
        return

    seen: set[tuple[str, str]] = set()
    for row in signals:
        signal_type = row.get("signal_type", "")
        detail = row.get("detail", "") or signal_type
        if signal_type == "style_correction":
            payload = {
                "scope": "user",
                "kind": "preference",
                "summary": "Keep visible replies strict caveman and short.",
                "confidence": 0.95,
                "source": "hook:style_correction",
            }
        elif signal_type == "user_correction":
            payload = {
                "scope": "user",
                "kind": "correction",
                "summary": detail,
                "confidence": 0.85,
                "source": "hook:user_correction",
            }
        elif signal_type == "wrong_context":
            payload = {
                "scope": "project",
                "kind": "mistake",
                "summary": detail,
                "confidence": 0.8,
                "source": "hook:wrong_context",
                "project_root": str(repo_root),
            }
        elif signal_type == "verified_success":
            payload = {
                "scope": "project",
                "kind": "verified_fact",
                "summary": detail,
                "confidence": 0.7,
                "source": "hook:verified_success",
                "project_root": str(repo_root),
            }
        elif signal_type == "verified_failure":
            payload = {
                "scope": "project",
                "kind": "mistake",
                "summary": detail,
                "confidence": 0.65,
                "source": "hook:verified_failure",
                "project_root": str(repo_root),
            }
        elif signal_type == "manual_learn":
            payload = {
                "scope": "project",
                "kind": "pattern",
                "summary": summary or detail,
                "confidence": 0.75,
                "source": "hook:manual_learn",
                "project_root": str(repo_root),
            }
        else:
            continue

        key = (payload["scope"], payload["summary"])
        if key in seen:
            continue
        seen.add(key)
        try:
            server.store_feedback(payload)
        except Exception:
            continue


def write_resume_artifacts(repo_root: Path, payload: dict, summary: str, workflow: dict) -> None:
    layout = state.ensure_project_layout(repo_root)
    turn_id = payload.get("turn_id", "unknown")
    checkpoint = {
        "timestamp": state.utc_now(),
        "turn_id": turn_id,
        "summary": summary,
        "phase": workflow.get("phase", "idle"),
        "route": workflow.get("route", "unknown"),
    }
    state.append_jsonl(layout["state"] / "turn-ledger.jsonl", checkpoint)
    (layout["state"] / "state-current.md").write_text(
        "\n".join(
            [
                "# Workflow State",
                "",
                f"- Phase: {workflow.get('phase', 'idle')}",
                f"- Route: {workflow.get('route', 'unknown')}",
                f"- Last task: {workflow.get('last_task', 'N/A')}",
                f"- Next step: {workflow.get('next_step', 'N/A')}",
                f"- Memory mode: {workflow.get('memory_mode', 'portable-markdown')}",
                f"- Updated: {workflow.get('updated_at', 'N/A')}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (layout["artifacts"] / "resume-note.md").write_text(
        "# Resume Note\n\n"
        f"Last: {summary or 'No summary.'}\n\n"
        f"Next: {workflow.get('next_step', 'N/A')}\n",
        encoding="utf-8",
    )


def main() -> None:
    payload = json.load(sys.stdin)
    if payload.get("stop_hook_active"):
        print(json.dumps({}))
        return

    repo_root = find_repo_root()
    if repo_root is None:
        print(json.dumps({}))
        return
    if state.acc_hooks_disabled(repo_root):
        print(json.dumps({}))
        return

    summary = session_summary(payload)
    signal_line, signals = recent_signal_summary(repo_root)
    updates = {
        "last_task": summary[:160] if summary else "",
        "active_task": summary[:160] if summary else "",
        "next_step": infer_next_step(summary),
        "next_action": infer_next_step(summary),
        "memory_mode": "portable-markdown",
    }
    workflow = state.write_state(repo_root, updates)
    state.append_jsonl(
        state.ensure_project_layout(repo_root)["state"] / "turn-ledger.jsonl",
        {
            "timestamp": state.utc_now(),
            "turn_id": payload.get("turn_id", "unknown"),
            "summary": summary,
            "phase": workflow.get("phase", "idle"),
            "route": workflow.get("route", "unknown"),
            "transaction_id": workflow.get("transaction_id", ""),
        },
    )
    write_mistake_ledger(repo_root, signals)
    durable_memory_writes(repo_root, signals, summary)
    print(json.dumps({}))


if __name__ == "__main__":
    try:
        main()
    except json.JSONDecodeError:
        print(json.dumps({"continue": False, "stopReason": "save_session.py: bad json in."}))
    except Exception as exc:  # pragma: no cover - hook best effort
        print(json.dumps({"continue": False, "stopReason": f"save_session.py: save fail: {exc}"}))
