"""
Save small session context.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import state
import model_ledger as _model_ledger


def record_session_model_outcome(repo_root: Path, payload: dict, signals: list[dict]) -> None:
    """Feed the model ledger so future sessions get real model recommendations."""
    recent_types = {row.get("signal_type") for row in signals[-12:]}
    if "verified_failure" in recent_types:
        outcome = "fail"
    elif "verified_success" in recent_types:
        outcome = "success"
    else:
        return
    ledger = state.ensure_project_layout(repo_root)["state"] / "model-ledger.jsonl"
    _model_ledger.record_model_result(
        _model_ledger.extract_model_from_payload(payload),
        "general",
        outcome,
        ledger_path=ledger,
    )


SESSION_SNAPSHOT_MAX_BYTES = 28672
SUMMARY_MAX_CHARS = 2000


def session_summary(payload: dict) -> str:
    text = payload.get("last_assistant_message") or ""
    if len(text) <= SUMMARY_MAX_CHARS:
        return text
    cut = text.rfind(" ", 0, SUMMARY_MAX_CHARS)
    if cut < SUMMARY_MAX_CHARS // 2:
        cut = SUMMARY_MAX_CHARS
    return text[:cut].rstrip() + "..."


def write_session_snapshot(repo_root: Path, summary: str, workflow: dict) -> None:
    content = [
        "# Anyone Can Code - Session Snapshot",
        "",
        "## Workflow Snapshot",
        f"- Phase: {workflow.get('phase', 'idle')}",
        f"- Route: {workflow.get('route', 'unknown')}",
        f"- Entry mode: {workflow.get('entry_mode', 'unknown')}",
        f"- Last task: {workflow.get('last_task', 'N/A')}",
        f"- Next step: {workflow.get('next_step', 'N/A')}",
        f"- Communication mode: {workflow.get('communication_mode', 'normal')}",
        f"- Memory mode: {workflow.get('memory_mode', 'portable-markdown')}",
        "",
        "## Last Session",
        summary or "No assistant summary was available.",
        "",
        "## Notes",
        "This file is generated by Anyone Can Code hooks and is safe to refresh.",
    ]
    text = "\n".join(content) + "\n"
    encoded = text.encode("utf-8")
    if len(encoded) > SESSION_SNAPSHOT_MAX_BYTES:
        text = encoded[:SESSION_SNAPSHOT_MAX_BYTES].decode("utf-8", errors="ignore")
        text = text[: text.rfind("\n")] + "\n"
    layout = state.ensure_project_layout(repo_root)
    (layout["state"] / "session-snapshot.md").write_text(text, encoding="utf-8")


def infer_next_step(summary: str) -> str:
    lower = summary.lower()
    if any(token in lower for token in ["fix", "error", "failure"]):
        return "Use $verify or $resume. Fix failure first."
    if any(token in lower for token in ["verify", "review"]):
        return "If clean, go on. If bad, fix."
    if any(token in lower for token in ["plan", "spec"]):
        return "Plan good. Build next."
    if any(token in lower for token in ["build", "implement", "change"]):
        return "Check result before done."
    return "Use front door or $status."


def recent_signal_summary(repo_root: Path) -> tuple[str, list[dict]]:
    signals = state.read_recent_jsonl(state.signal_log_path(repo_root), limit=12)
    if not signals:
        return "No recent signals.", []
    recent_types = [row.get("signal_type", "unknown") for row in signals[-5:]]
    return f"Recent signals: {', '.join(recent_types)}.", signals


def write_mistake_ledger(repo_root: Path, signals: list[dict]) -> None:
    for row in signals:
        if row.get("signal_type") in {"style_correction", "user_correction", "wrong_context", "repeated_failure"}:
            state.append_jsonl(
                state.mistake_log_path(repo_root),
                {
                    "timestamp": row.get("timestamp", state.utc_now()),
                    "signal_type": row.get("signal_type"),
                    "detail": row.get("detail", ""),
                },
            )


def maybe_import_memory_server():
    plugin_root = os.environ.get("PLUGIN_ROOT")
    if not plugin_root:
        return None
    server_path = Path(plugin_root) / "mcp"
    if not server_path.exists():
        return None
    sys.path.insert(0, str(server_path))
    try:
        import server  # type: ignore

        return server
    except Exception:
        return None


def durable_memory_writes(repo_root: Path, signals: list[dict], summary: str) -> str:
    """Write durable lessons; return a proof line ("" when nothing was written)."""
    server = maybe_import_memory_server()
    layout = state.ensure_project_layout(repo_root)
    notes_dir: Path = layout["memory"] / "notes"
    notes_dir.mkdir(parents=True, exist_ok=True)

    from datetime import date
    today = date.today().isoformat()
    note_file = notes_dir / f"{today}.md"

    written = 0
    seen: set[tuple[str, str]] = set()
    for row in signals:
        signal_type = row.get("signal_type", "")
        detail = row.get("detail", "") or signal_type

        if signal_type not in {"style_correction", "user_correction", "wrong_context",
                               "verified_success", "verified_failure", "manual_learn"}:
            continue

        key = (signal_type, detail)
        if key in seen:
            continue
        seen.add(key)

        # Always write disk fallback
        entry = f"- [{row.get('timestamp', state.utc_now())}] ({signal_type}) {detail}\n"
        with note_file.open("a", encoding="utf-8") as f:
            f.write(entry)
        written += 1

        # Also try MCP server
        if server is None:
            continue
        if signal_type == "style_correction":
            payload = {"scope": "user", "kind": "preference",
                       "summary": "Keep visible replies strict caveman and short.",
                       "confidence": 0.95, "source": "hook:style_correction"}
        elif signal_type == "user_correction":
            payload = {"scope": "user", "kind": "correction",
                       "summary": detail, "confidence": 0.85, "source": "hook:user_correction"}
        elif signal_type == "wrong_context":
            payload = {"scope": "project", "kind": "mistake", "summary": detail,
                       "confidence": 0.8, "source": "hook:wrong_context",
                       "project_root": str(repo_root)}
        elif signal_type == "verified_success":
            payload = {"scope": "project", "kind": "verified_fact", "summary": detail,
                       "confidence": 0.7, "source": "hook:verified_success",
                       "project_root": str(repo_root)}
        elif signal_type == "verified_failure":
            payload = {"scope": "project", "kind": "mistake", "summary": detail,
                       "confidence": 0.65, "source": "hook:verified_failure",
                       "project_root": str(repo_root)}
        elif signal_type == "manual_learn":
            payload = {"scope": "project", "kind": "pattern",
                       "summary": summary or detail, "confidence": 0.75,
                       "source": "hook:manual_learn", "project_root": str(repo_root)}
        else:
            continue
        try:
            server.store_feedback(payload)
        except Exception:
            continue

    if written == 0:
        return ""
    return f"{state.utc_now()} wrote {written} lesson(s) to memory/notes/{note_file.name}"


def write_resume_artifacts(repo_root: Path, payload: dict, summary: str, workflow: dict) -> None:
    layout = state.ensure_project_layout(repo_root)
    (layout["state"] / "state-current.md").write_text(
        "\n".join(
            [
                "# Workflow State",
                "",
                f"- Phase: {workflow.get('phase', 'idle')}",
                f"- Route: {workflow.get('route', 'unknown')}",
                f"- Last task: {workflow.get('last_task', 'N/A')}",
                f"- Next step: {workflow.get('next_step', 'N/A')}",
                f"- Memory mode: {workflow.get('memory_mode', 'portable-markdown')}",
                f"- Updated: {workflow.get('updated_at', 'N/A')}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    # Portable cross-tool bag (docs: wrap native resume; ACC owns work truth).
    try:
        scripts = Path(__file__).resolve().parents[2] / "scripts"
        if str(scripts) not in sys.path:
            sys.path.insert(0, str(scripts))
        import portable_handoff as _portable_handoff  # type: ignore

        session_id = str(payload.get("session_id") or "")
        _portable_handoff.write_portable_handoff(
            repo_root,
            workflow,
            tool_left="codex",
            session_id=session_id,
            summary=summary or "",
            skip_if_empty=True,
        )
    except Exception:
        (layout["artifacts"] / "resume-note.md").write_text(
            "# Resume Note\n\n"
            f"Last: {summary or 'No summary.'}\n\n"
            f"Next: {workflow.get('next_step') or workflow.get('next_action') or 'N/A'}\n",
            encoding="utf-8",
        )


def wiki_stop_proposals(repo_root: Path, summary: str, write_proof: str) -> str:
    """Propose (not auto-write) 1–3 wiki saves when no durable write ran."""
    if write_proof:
        return ""
    try:
        scripts = Path(__file__).resolve().parents[2] / "scripts"
        if str(scripts) not in sys.path:
            sys.path.insert(0, str(scripts))
        import wiki_memory as _wiki_memory  # type: ignore

        # Prefer decision-like sentences from the turn summary.
        chunks = [c.strip() for c in re.split(r"[.\n]+", summary or "") if c.strip()]
        return _wiki_memory.stop_save_prompt(chunks)
    except Exception:
        return ""


def handle_payload(payload: dict, repo_root: Path) -> dict:
    if payload.get("stop_hook_active"):
        return {}

    summary = session_summary(payload)
    signal_line, signals = recent_signal_summary(repo_root)
    write_mistake_ledger(repo_root, signals)
    record_session_model_outcome(repo_root, payload, signals)
    write_proof = durable_memory_writes(repo_root, signals, summary)
    # Keep human wiki index/log in sync when durable disk notes landed without MCP.
    if write_proof:
        try:
            scripts = Path(__file__).resolve().parents[2] / "scripts"
            if str(scripts) not in sys.path:
                sys.path.insert(0, str(scripts))
            import wiki_memory as _wiki_memory  # type: ignore

            mem = state.ensure_project_layout(repo_root)["memory"]
            _wiki_memory.rebuild_human_index(mem)
            _wiki_memory.append_log(mem, "session-save", write_proof[:160])
        except Exception:
            pass
    updates = {
        "last_task": summary or "",
        "active_task": summary or "",
        "next_step": infer_next_step(summary),
        "next_action": infer_next_step(summary),
        "memory_mode": "portable-markdown",
    }
    if write_proof:
        updates["memory_write_proof"] = write_proof
    workflow = state.write_state(repo_root, updates)
    write_session_snapshot(repo_root, summary, workflow)
    write_resume_artifacts(repo_root, payload, summary, workflow)
    state.append_jsonl(
        state.ensure_project_layout(repo_root)["state"] / "turn-ledger.jsonl",
        {
            "timestamp": state.utc_now(),
            "turn_id": payload.get("turn_id", "unknown"),
            "summary": summary,
            "phase": workflow.get("phase", "idle"),
            "route": workflow.get("route", "unknown"),
            "transaction_id": workflow.get("transaction_id", ""),
        },
    )
    proposal = wiki_stop_proposals(repo_root, summary, write_proof)
    if proposal:
        return {"systemMessage": proposal}
    return {}


def main() -> None:
    payload = json.load(sys.stdin)
    resolution = state.resolve_hook_project(payload)
    print(
        json.dumps(
            state.run_hook_attempt(
                resolution,
                "save_session",
                payload,
                lambda: handle_payload(payload, Path(resolution["project_root"])),
            )
        )
    )


if __name__ == "__main__":
    try:
        main()
    except json.JSONDecodeError:
        print(json.dumps({}))
    except Exception as exc:  # pragma: no cover - hook best effort
        print(json.dumps({}))
